workdir: /MP_Data/Dados_David/repressors_pipeline

threads: 4
project_name: DNA_repressores
samples:
    'sample_01':
        forward: 'data/sample_01_R1.fastq'
        reverseR: 'data/sample_01_R2.fastq'
    'sample_02':
        forward: 'data/sample_02_R1.fastq'
        reverseR: 'data/sample_02_R2.fastq'
